import type { HeroDef } from '../domain/types'

/** 兼容 GitHub Pages 子路径 */
function withBase(path: string): string {
  const base = import.meta.env.BASE_URL || '/'
  return base.endsWith('/') ? base + path.replace(/^\//, '') : base + '/' + path.replace(/^\//, '')
}

/** 火炬无限 wiki 全英雄形态（26），头像本地 public/heroes */
export const HEROES: HeroDef[] = [
  {
    id: 'rehan_anger',
    name: '狂人 雷恩',
    pathName: '怒火',
    title: '狂人 雷恩|怒火',
    description: '攻击与受伤积攒怒气，满怒暴气，高危高伤选项。',
    resourceName: '怒气',
    resourceMax: 100,
    baseAttrs: { str: 6, agi: 3, int: 2, con: 5, luck: 3, will: 4 },
    startArtIds: ['leap_attack', 'focused_slash'],
    tags: ['attack', 'melee', 'rage'],
    portrait: withBase('heroes/rehan_anger.webp'),
    wikiPath: 'Anger',
  },
  {
    id: 'rehan_shadow',
    name: '狂人 雷恩',
    pathName: '怒影',
    title: '狂人 雷恩|怒影',
    description: '祖灵庇佑，召唤愠怒之灵协同作战，召唤与群战更强。',
    resourceName: '怒影',
    resourceMax: 100,
    baseAttrs: { str: 5, agi: 3, int: 3, con: 5, luck: 3, will: 4 },
    startArtIds: ['whirlwind', 'resurrection_warcry'],
    tags: ['attack', 'minion', 'rage'],
    portrait: withBase('heroes/rehan_shadow.webp'),
    wikiPath: 'Seething_Silhouette',
  },
  {
    id: 'carino_glory',
    name: '圣枪 卡里诺',
    pathName: '荣光游侠',
    title: '圣枪 卡里诺|荣光游侠',
    description: '特殊弹药组合射击，远程与消耗性强化选项。',
    resourceName: '弹药',
    resourceMax: 30,
    baseAttrs: { str: 4, agi: 6, int: 3, con: 3, luck: 4, will: 3 },
    startArtIds: ['split_shot', 'rain_of_arrows'],
    tags: ['ranged', 'projectile'],
    portrait: withBase('heroes/carino_glory.webp'),
    wikiPath: 'Ranger_of_Glory',
  },
  {
    id: 'carino_lethal',
    name: '圣枪 卡里诺',
    pathName: '至暗掠影',
    title: '圣枪 卡里诺|至暗掠影',
    description: '控制射程与偏斜，远程输出与生存兼顾。',
    resourceName: '偏斜',
    resourceMax: 10,
    baseAttrs: { str: 3, agi: 6, int: 4, con: 3, luck: 4, will: 3 },
    startArtIds: ['ice_shot', 'blink'],
    tags: ['ranged', 'defense'],
    portrait: withBase('heroes/carino_lethal.webp'),
    wikiPath: 'Lethal_Flash',
  },
  {
    id: 'carino_zealot',
    name: '圣枪 卡里诺',
    pathName: '战火狂徒',
    title: '圣枪 卡里诺|战火狂徒',
    description: '射击模式与过热，爆发强但需装填。',
    resourceName: '枪温',
    resourceMax: 100,
    baseAttrs: { str: 5, agi: 5, int: 3, con: 4, luck: 3, will: 3 },
    startArtIds: ['hammer_of_ash', 'split_shot'],
    tags: ['ranged', 'fire', 'burst'],
    portrait: withBase('heroes/carino_zealot.webp'),
    wikiPath: 'Zealot_of_War',
  },
  {
    id: 'erika_wind',
    name: '猫眼 艾瑞卡',
    pathName: '疾风追猎',
    title: '猫眼 艾瑞卡|疾风追猎',
    description: '移速与追猎，潜行、撤离与连续猎杀占优。',
    resourceName: '追猎',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 7, int: 3, con: 3, luck: 5, will: 3 },
    startArtIds: ['blink', 'split_shot'],
    tags: ['agility', 'hunt', 'ranged'],
    portrait: withBase('heroes/erika_wind.webp'),
    wikiPath: 'Wind_Stalker',
  },
  {
    id: 'erika_lightning',
    name: '猫眼 艾瑞卡',
    pathName: '电光猫影',
    title: '猫眼 艾瑞卡|电光猫影',
    description: '闪电与猫影麻痹，范围控场与爆发。',
    resourceName: '电光',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 6, int: 5, con: 3, luck: 4, will: 3 },
    startArtIds: ['chain_lightning', 'blink'],
    tags: ['lightning', 'agility'],
    portrait: withBase('heroes/erika_lightning.webp'),
    wikiPath: 'Lightning_Shadow',
  },
  {
    id: 'erika_vendetta',
    name: '猫眼 艾瑞卡',
    pathName: '寻仇之刺',
    title: '猫眼 艾瑞卡|寻仇之刺',
    description: '刺客近战，疾速穿梭，锋利连刺。',
    resourceName: '仇意',
    resourceMax: 100,
    baseAttrs: { str: 5, agi: 7, int: 2, con: 3, luck: 4, will: 3 },
    startArtIds: ['double_thrusts', 'shadow_dash'],
    tags: ['melee', 'assassin', 'agility'],
    portrait: withBase('heroes/erika_vendetta.webp'),
    wikiPath: "Vendetta's_Sting",
  },
  {
    id: 'bing_blast',
    name: '逃脱者 宾',
    pathName: '爆破新星',
    title: '逃脱者 宾|爆破新星',
    description: '炸弹封装投射，瞬间多段爆炸伤害。',
    resourceName: '炸弹',
    resourceMax: 12,
    baseAttrs: { str: 4, agi: 5, int: 5, con: 3, luck: 5, will: 3 },
    startArtIds: ['split_firebolt', 'leap_attack'],
    tags: ['bomb', 'fire', 'craft'],
    portrait: withBase('heroes/bing_blast.webp'),
    wikiPath: 'Blast_Nova',
  },
  {
    id: 'bing_creative',
    name: '逃脱者 宾',
    pathName: '创想鬼才',
    title: '逃脱者 宾|创想鬼才',
    description: '灵感机与奇思妙想，法术超载与机关。',
    resourceName: '灵感',
    resourceMax: 100,
    baseAttrs: { str: 2, agi: 4, int: 7, con: 3, luck: 5, will: 3 },
    startArtIds: ['split_firebolt', 'chain_lightning'],
    tags: ['spell', 'craft', 'gadget'],
    portrait: withBase('heroes/bing_creative.webp'),
    wikiPath: 'Creative_Genius',
  },
  {
    id: 'gemma_flame',
    name: '冰焰 吉玛',
    pathName: '欢愉之焰',
    title: '冰焰 吉玛|欢愉之焰',
    description: '炼狱削弱敌人，火焰输出强化。',
    resourceName: '欢愉',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 3, int: 6, con: 4, luck: 4, will: 4 },
    startArtIds: ['split_firebolt', 'flame_slash'],
    tags: ['fire', 'spell'],
    portrait: withBase('heroes/gemma_flame.webp'),
    wikiPath: 'Flame_of_Pleasure',
  },
  {
    id: 'gemma_frost',
    name: '冰焰 吉玛',
    pathName: '冰结之心',
    title: '冰焰 吉玛|冰结之心',
    description: '冰能量叠层，冰霜脉冲与控制。',
    resourceName: '冰能',
    resourceMax: 100,
    baseAttrs: { str: 2, agi: 3, int: 7, con: 4, luck: 3, will: 4 },
    startArtIds: ['ice_shot', 'ring_of_ice'],
    tags: ['cold', 'spell'],
    portrait: withBase('heroes/gemma_frost.webp'),
    wikiPath: 'Frostbitten_Heart',
  },
  {
    id: 'gemma_fusion',
    name: '冰焰 吉玛',
    pathName: '冰火融合',
    title: '冰焰 吉玛|冰火融合',
    description: '冰火交融叠融合能量，暴走爆发。',
    resourceName: '融合',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 3, int: 6, con: 4, luck: 4, will: 4 },
    startArtIds: ['split_firebolt', 'blizzard'],
    tags: ['fire', 'cold', 'fusion'],
    portrait: withBase('heroes/gemma_fusion.webp'),
    wikiPath: 'Ice-Fire_Fusion',
  },
  {
    id: 'thea_wisdom',
    name: '神谕者 希雅',
    pathName: '众神之伟智',
    title: '神谕者 希雅|众神之伟智',
    description: '坚韧/聚能/灵动祝福，消耗强化神赐。',
    resourceName: '祝福',
    resourceMax: 12,
    baseAttrs: { str: 3, agi: 3, int: 6, con: 4, luck: 4, will: 5 },
    startArtIds: ['stoneskin', 'resurrection_warcry'],
    tags: ['blessing', 'support'],
    portrait: withBase('heroes/thea_wisdom.webp'),
    wikiPath: 'Wisdom_of_The_Gods',
  },
  {
    id: 'thea_incarnation',
    name: '神谕者 希雅',
    pathName: '众神之化身',
    title: '神谕者 希雅|众神之化身',
    description: '神域内外切换，灵动周旋与坚韧硬刚。',
    resourceName: '神域',
    resourceMax: 100,
    baseAttrs: { str: 4, agi: 4, int: 5, con: 5, luck: 3, will: 5 },
    startArtIds: ['stoneskin', 'focused_slash'],
    tags: ['blessing', 'domain'],
    portrait: withBase('heroes/thea_incarnation.webp'),
    wikiPath: 'Incarnation_of_the_Gods',
  },
  {
    id: 'thea_blasphemer',
    name: '神谕者 希雅',
    pathName: '渎神',
    title: '神谕者 希雅|渎神',
    description: '祝福化亵渎，单体腐蚀与范围爆炸。',
    resourceName: '亵渎',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 3, int: 7, con: 3, luck: 4, will: 4 },
    startArtIds: ['shadow_shot', 'split_firebolt'],
    tags: ['erosion', 'spell', 'demon'],
    portrait: withBase('heroes/thea_blasphemer.webp'),
    wikiPath: 'Blasphemer',
  },
  {
    id: 'youga_illusion',
    name: '时空见证者 尤加',
    pathName: '时空幻象',
    title: '时空见证者 尤加|时空幻象',
    description: '扭曲时空与幻象分身，协同施法。',
    resourceName: '时流',
    resourceMax: 100,
    baseAttrs: { str: 2, agi: 4, int: 7, con: 3, luck: 5, will: 4 },
    startArtIds: ['blink', 'chain_lightning'],
    tags: ['time', 'spell', 'illusion'],
    portrait: withBase('heroes/youga_illusion.webp'),
    wikiPath: 'Spacetime_Illusion',
  },
  {
    id: 'youga_elapse',
    name: '时空见证者 尤加',
    pathName: '时空流逝',
    title: '时空见证者 尤加|时空流逝',
    description: '对敌扭曲时空，加速持续伤害。',
    resourceName: '乱流',
    resourceMax: 100,
    baseAttrs: { str: 2, agi: 3, int: 7, con: 3, luck: 4, will: 5 },
    startArtIds: ['shadow_shot', 'blizzard'],
    tags: ['time', 'dot', 'spell'],
    portrait: withBase('heroes/youga_elapse.webp'),
    wikiPath: 'Spacetime_Elapse',
  },
  {
    id: 'moto_order',
    name: '指挥官 莫托',
    pathName: '号令征召',
    title: '指挥官 莫托|号令征召',
    description: '智械大军与超载强化召唤物。',
    resourceName: '统御',
    resourceMax: 100,
    baseAttrs: { str: 4, agi: 2, int: 6, con: 5, luck: 3, will: 4 },
    startArtIds: ['stoneskin', 'resurrection_warcry'],
    tags: ['minion', 'machine'],
    portrait: withBase('heroes/moto_order.webp'),
    wikiPath: 'Order_Calling',
  },
  {
    id: 'moto_charge',
    name: '指挥官 莫托',
    pathName: '冲锋征召',
    title: '指挥官 莫托|冲锋征召',
    description: '智械冲锋自爆，短时高频召唤。',
    resourceName: '超载',
    resourceMax: 100,
    baseAttrs: { str: 5, agi: 3, int: 5, con: 5, luck: 3, will: 3 },
    startArtIds: ['leap_attack', 'hammer_of_ash'],
    tags: ['minion', 'burst', 'machine'],
    portrait: withBase('heroes/moto_charge.webp'),
    wikiPath: 'Charge_Calling',
  },
  {
    id: 'rosa_chariot',
    name: '光曜 罗莎',
    pathName: '圣庭战车',
    title: '光曜 罗莎|圣庭战车',
    description: '圣光领域聚敌，领域内增益。',
    resourceName: '圣光',
    resourceMax: 100,
    baseAttrs: { str: 5, agi: 3, int: 4, con: 5, luck: 3, will: 5 },
    startArtIds: ['focused_slash', 'resurrection_warcry'],
    tags: ['holy', 'melee', 'domain'],
    portrait: withBase('heroes/rosa_chariot.webp'),
    wikiPath: 'High_Court_Chariot',
  },
  {
    id: 'rosa_blade',
    name: '光曜 罗莎',
    pathName: '无垢之刃',
    title: '光曜 罗莎|无垢之刃',
    description: '秘银净土元素输出，魔力养成向。',
    resourceName: '净土',
    resourceMax: 100,
    baseAttrs: { str: 4, agi: 4, int: 5, con: 4, luck: 3, will: 5 },
    startArtIds: ['flame_slash', 'stoneskin'],
    tags: ['holy', 'element', 'spell'],
    portrait: withBase('heroes/rosa_blade.webp'),
    wikiPath: 'Unsullied_Blade',
  },
  {
    id: 'iris_growing',
    name: '遗世魔灵 伊瑞斯',
    pathName: '生长的微风',
    title: '遗世魔灵 伊瑞斯|生长的微风',
    description: '魔灵伙伴养成，加速生长与增益。',
    resourceName: '微风',
    resourceMax: 100,
    baseAttrs: { str: 2, agi: 4, int: 5, con: 4, luck: 5, will: 4 },
    startArtIds: ['stoneskin', 'blink'],
    tags: ['minion', 'spirit', 'support'],
    portrait: withBase('heroes/iris_growing.webp'),
    wikiPath: 'Growing_Breeze',
  },
  {
    id: 'iris_vigilant',
    name: '遗世魔灵 伊瑞斯',
    pathName: '守望的暖风',
    title: '遗世魔灵 伊瑞斯|守望的暖风',
    description: '与魔灵融合守望，使用魔灵技能作战。',
    resourceName: '暖风',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 4, int: 6, con: 4, luck: 4, will: 4 },
    startArtIds: ['split_firebolt', 'chain_lightning'],
    tags: ['minion', 'spirit', 'spell'],
    portrait: withBase('heroes/iris_vigilant.webp'),
    wikiPath: 'Vigilant_Breeze',
  },
  {
    id: 'selena_tide',
    name: '汐语 赛琳娜',
    pathName: '与海潮同歌',
    title: '汐语 赛琳娜|与海潮同歌',
    description: '吟游/高歌双形态，海潮场地强化输出。',
    resourceName: '海潮',
    resourceMax: 100,
    baseAttrs: { str: 3, agi: 5, int: 5, con: 3, luck: 5, will: 4 },
    startArtIds: ['blizzard', 'resurrection_warcry'],
    tags: ['tide', 'spell', 'song'],
    portrait: withBase('heroes/selena_tide.webp'),
    wikiPath: 'Sing_with_the_Tide',
  },
  {
    id: 'sage_licorice',
    name: '药香师 赛琪',
    pathName: '甘草前调',
    title: '药香师 赛琪|甘草前调',
    description: '配药高手，炼丹疗伤与资源转化更强。',
    resourceName: '灵药',
    resourceMax: 5,
    baseAttrs: { str: 2, agi: 3, int: 6, con: 4, luck: 4, will: 5 },
    startArtIds: ['stoneskin', 'split_firebolt'],
    tags: ['alchemy', 'support', 'spell'],
    portrait: withBase('heroes/sage_licorice.webp'),
    wikiPath: 'Licorice_Note',
  },
]

export function getHero(id: string): HeroDef {
  const h = HEROES.find((x) => x.id === id)
  if (!h) throw new Error(`未知英雄: ${id}`)
  return h
}
