import type { TalentDef } from '../domain/types'

export const PROFESSIONS = [
  { id: 'god_of_might', name: '巨力之神', tags: ['attack', 'str'] },
  { id: 'goddess_of_hunting', name: '狩猎之神', tags: ['speed', 'agi'] },
  { id: 'goddess_of_knowledge', name: '知识之神', tags: ['spell', 'int'] },
  { id: 'god_of_war', name: '征战之神', tags: ['physical', 'str', 'agi'] },
  { id: 'goddess_of_deception', name: '欺诈之神', tags: ['dot', 'erosion', 'agi', 'int'] },
  { id: 'god_of_machines', name: '机械之神', tags: ['minion', 'str', 'int'] },
  { id: 'new_god', name: '新神', tags: ['all'], rare: true },
] as const

export const CORE_TALENTS: TalentDef[] = [
  {
    id: 'taotai',
    name: '淘汰',
    kind: 'core',
    professionId: 'god_of_might',
    professionName: '巨力之神',
    description: '攻击击中时，淘汰生命值过低的敌人。映射：战斗残血斩杀检定。',
    effects: [
      { type: 'attr', key: 'str', value: 2 },
      { type: 'combat', key: 'execute', value: 18 },
      { type: 'rule', id: 'execute_low_hp' },
    ],
    tags: ['attack'],
  },
  {
    id: 'jieshi',
    name: '借势',
    kind: 'core',
    professionId: 'god_of_might',
    professionName: '巨力之神',
    description: '蓄势一击，击败后刷新。映射：战斗爆发选项增强。',
    effects: [
      { type: 'attr', key: 'str', value: 1 },
      { type: 'combat', key: 'burst', value: 15 },
    ],
    tags: ['attack'],
  },
  {
    id: 'jianren',
    name: '坚韧',
    kind: 'core',
    professionId: 'god_of_might',
    professionName: '巨力之神',
    description: '击中获得坚韧祝福。映射：体魄与硬抗检定。',
    effects: [
      { type: 'attr', key: 'con', value: 2 },
      { type: 'checkBonus', tags: ['endure', 'breakthrough'], value: 8 },
    ],
    tags: ['defense'],
  },
  {
    id: 'shidalichen',
    name: '势大力沉',
    kind: 'core',
    professionId: 'god_of_might',
    professionName: '巨力之神',
    description: '攻击更重、更慢。映射：攻↑敏↓。',
    effects: [
      { type: 'attr', key: 'str', value: 3 },
      { type: 'attr', key: 'agi', value: -1 },
    ],
    tags: ['attack'],
  },
  {
    id: 'minrui',
    name: '敏锐',
    kind: 'core',
    professionId: 'goddess_of_hunting',
    professionName: '狩猎之神',
    description: '击中获得灵动祝福。映射：敏与探险。',
    effects: [
      { type: 'attr', key: 'agi', value: 2 },
      { type: 'checkBonus', tags: ['explore', 'escape'], value: 10 },
    ],
    tags: ['speed'],
  },
  {
    id: 'xingsecongcong',
    name: '行色匆匆',
    kind: 'core',
    professionId: 'goddess_of_hunting',
    professionName: '狩猎之神',
    description: '移动后增伤。映射：探险耗时-1月（最少1）。',
    effects: [
      { type: 'attr', key: 'agi', value: 1 },
      { type: 'rule', id: 'explore_faster' },
      { type: 'combat', key: 'damage', value: 8 },
    ],
    tags: ['speed'],
  },
  {
    id: 'shishiwuchang',
    name: '世事无常',
    kind: 'core',
    professionId: 'goddess_of_hunting',
    professionName: '狩猎之神',
    description: '伤害更极端。映射：大成功/大失败权重↑。',
    effects: [
      { type: 'attr', key: 'luck', value: 2 },
      { type: 'rule', id: 'extreme_rolls' },
    ],
    tags: ['luck'],
  },
  {
    id: 'yijiansandiao',
    name: '一箭三雕',
    kind: 'core',
    professionId: 'goddess_of_hunting',
    professionName: '狩猎之神',
    description: '投射物数量增加。映射：远程与多目标。',
    effects: [
      { type: 'attr', key: 'agi', value: 1 },
      { type: 'combat', key: 'projectile', value: 12 },
    ],
    tags: ['ranged'],
  },
  {
    id: 'biejuhuiyan',
    name: '别具慧眼',
    kind: 'core',
    professionId: 'goddess_of_knowledge',
    professionName: '知识之神',
    description: '法术更强，消耗更高。映射：智↑闭关↑。',
    effects: [
      { type: 'attr', key: 'int', value: 2 },
      { type: 'cultivateMult', value: 0.12 },
    ],
    tags: ['spell'],
  },
  {
    id: 'kuhan',
    name: '苦寒',
    kind: 'core',
    professionId: 'goddess_of_knowledge',
    professionName: '知识之神',
    description: '击中获得聚能祝福。映射：术法检定。',
    effects: [
      { type: 'attr', key: 'int', value: 2 },
      { type: 'checkBonus', tags: ['spell', 'insight'], value: 10 },
    ],
    tags: ['spell'],
  },
  {
    id: 'dengta',
    name: '灯塔',
    kind: 'core',
    professionId: 'goddess_of_knowledge',
    professionName: '知识之神',
    description: '法术迸发更强。映射：关键术法爆发。',
    effects: [
      { type: 'attr', key: 'int', value: 1 },
      { type: 'combat', key: 'spell_burst', value: 15 },
    ],
    tags: ['spell'],
  },
  {
    id: 'qihuanmoce',
    name: '奇幻莫测',
    kind: 'core',
    professionId: 'goddess_of_knowledge',
    professionName: '知识之神',
    description: '额外纠缠。映射：控场与奇遇。',
    effects: [
      { type: 'attr', key: 'int', value: 1 },
      { type: 'attr', key: 'luck', value: 1 },
      { type: 'eventWeight', tags: ['adventure'], mult: 1.15 },
    ],
    tags: ['spell'],
  },
  {
    id: 'ningju',
    name: '凝聚',
    kind: 'core',
    professionId: 'god_of_war',
    professionName: '征战之神',
    description: '周期性暴击蓄势。映射：PK 先手。',
    effects: [
      { type: 'attr', key: 'str', value: 1 },
      { type: 'attr', key: 'agi', value: 1 },
      { type: 'combat', key: 'crit', value: 12 },
    ],
    tags: ['physical'],
  },
  {
    id: 'jianqiang',
    name: '坚强',
    kind: 'core',
    professionId: 'god_of_war',
    professionName: '征战之神',
    description: '巨额伤害后有几率保留一息。映射：本局首次致死→濒死。',
    effects: [
      { type: 'attr', key: 'con', value: 2 },
      { type: 'rule', id: 'second_wind' },
    ],
    tags: ['defense'],
  },
  {
    id: 'yexin',
    name: '野心',
    kind: 'core',
    professionId: 'god_of_war',
    professionName: '征战之神',
    description: '战意积攒。映射：连战与杀伐。',
    effects: [
      { type: 'attr', key: 'will', value: 1 },
      { type: 'combat', key: 'war_intent', value: 10 },
      { type: 'eventWeight', tags: ['combat'], mult: 1.2 },
    ],
    tags: ['physical'],
  },
  {
    id: 'yinli',
    name: '引力',
    kind: 'core',
    professionId: 'god_of_war',
    professionName: '征战之神',
    description: '近战更强。映射：近战检定。',
    effects: [
      { type: 'attr', key: 'str', value: 2 },
      { type: 'checkBonus', tags: ['melee', 'combat'], value: 8 },
    ],
    tags: ['melee'],
  },
  {
    id: 'jinjililiang',
    name: '禁忌力量',
    kind: 'core',
    professionId: 'goddess_of_deception',
    professionName: '欺诈之神',
    description: '腐蚀更强，抗性下降。映射：魔道权重↑正道难度↑。',
    effects: [
      { type: 'attr', key: 'int', value: 2 },
      { type: 'attr', key: 'con', value: -1 },
      { type: 'eventWeight', tags: ['demon'], mult: 1.35 },
    ],
    tags: ['erosion'],
  },
  {
    id: 'qianyimohua',
    name: '潜移默化',
    kind: 'core',
    professionId: 'goddess_of_deception',
    professionName: '欺诈之神',
    description: '迷踪时持续伤害。映射：阴诡选项。',
    effects: [
      { type: 'attr', key: 'agi', value: 1 },
      { type: 'attr', key: 'luck', value: 1 },
      { type: 'checkBonus', tags: ['stealth', 'trade'], value: 8 },
    ],
    tags: ['dot'],
  },
  {
    id: 'wenyi',
    name: '瘟疫',
    kind: 'core',
    professionId: 'goddess_of_deception',
    professionName: '欺诈之神',
    description: '凋零与移动。映射：毒伤与追击。',
    effects: [
      { type: 'attr', key: 'int', value: 1 },
      { type: 'combat', key: 'dot', value: 12 },
    ],
    tags: ['dot'],
  },
  {
    id: 'haoling',
    name: '号令',
    kind: 'core',
    professionId: 'god_of_machines',
    professionName: '机械之神',
    description: '召唤物更强。映射：机关/傀儡选项。',
    effects: [
      { type: 'attr', key: 'int', value: 1 },
      { type: 'attr', key: 'con', value: 1 },
      { type: 'combat', key: 'minion', value: 15 },
      { type: 'rule', id: 'minion_options' },
    ],
    tags: ['minion'],
  },
  {
    id: 'guisuo',
    name: '龟缩',
    kind: 'core',
    professionId: 'god_of_machines',
    professionName: '机械之神',
    description: '屏障防护。映射：减伤与布阵。',
    effects: [
      { type: 'attr', key: 'con', value: 2 },
      { type: 'checkBonus', tags: ['defend', 'endure'], value: 10 },
    ],
    tags: ['defense'],
  },
  {
    id: 'shaobing',
    name: '哨兵',
    kind: 'core',
    professionId: 'god_of_machines',
    professionName: '机械之神',
    description: '哨卫数量。映射：布置禁制。',
    effects: [
      { type: 'attr', key: 'int', value: 1 },
      { type: 'combat', key: 'sentry', value: 10 },
    ],
    tags: ['minion'],
  },
  {
    id: 'longxijue',
    name: '龙息绝',
    kind: 'core',
    professionId: 'new_god',
    professionName: '新神',
    description: '吞噬坚韧后爆发。映射：高风险爆发规则。',
    effects: [
      { type: 'attr', key: 'str', value: 2 },
      { type: 'attr', key: 'will', value: 1 },
      { type: 'combat', key: 'burst', value: 20 },
      { type: 'eventWeight', tags: ['risk'], mult: 1.25 },
    ],
    tags: ['all'],
  },
]

export const NODE_TALENTS: TalentDef[] = [
  {
    id: 'n_dmg_s',
    name: '小型天赋·伤害',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '+伤害 → 攻+1',
    effects: [{ type: 'attr', key: 'str', value: 1 }],
    tags: ['attack'],
    weight: 10,
  },
  {
    id: 'n_spd_s',
    name: '小型天赋·攻速',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '+攻击速度 → 敏+1',
    effects: [{ type: 'attr', key: 'agi', value: 1 }],
    tags: ['speed'],
    weight: 10,
  },
  {
    id: 'n_life_s',
    name: '小型天赋·生命',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '+最大生命 → 体+1',
    effects: [{ type: 'attr', key: 'con', value: 1 }],
    tags: ['life'],
    weight: 10,
  },
  {
    id: 'n_spell_s',
    name: '小型天赋·法术',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '+法术倾向 → 智+1',
    effects: [{ type: 'attr', key: 'int', value: 1 }],
    tags: ['spell'],
    weight: 8,
  },
  {
    id: 'n_luck_s',
    name: '小型天赋·气运',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '奇遇倾向 → 运+1',
    effects: [{ type: 'attr', key: 'luck', value: 1 }],
    tags: ['luck'],
    weight: 6,
  },
  {
    id: 'n_will_s',
    name: '小型天赋·道心',
    kind: 'small',
    professionId: 'any',
    professionName: '通用',
    description: '心志 → 志+1',
    effects: [{ type: 'attr', key: 'will', value: 1 }],
    tags: ['will'],
    weight: 6,
  },
  {
    id: 'n_dmg_m',
    name: '中型天赋·伤害',
    kind: 'medium',
    professionId: 'any',
    professionName: '通用',
    description: '更高伤害 → 攻+2',
    effects: [{ type: 'attr', key: 'str', value: 2 }],
    tags: ['attack'],
    weight: 5,
  },
  {
    id: 'n_life_m',
    name: '中型天赋·生命护甲',
    kind: 'medium',
    professionId: 'any',
    professionName: '通用',
    description: '生命与护甲 → 体+2',
    effects: [{ type: 'attr', key: 'con', value: 2 }],
    tags: ['life'],
    weight: 5,
  },
  {
    id: 'n_cult_m',
    name: '中型天赋·悟性',
    kind: 'medium',
    professionId: 'any',
    professionName: '通用',
    description: '闭关效率 +8%',
    effects: [{ type: 'cultivateMult', value: 0.08 }],
    tags: ['cultivate'],
    weight: 4,
  },
  {
    id: 'n_leg_str',
    name: '传奇中型·刚猛',
    kind: 'legendary_medium',
    professionId: 'any',
    professionName: '通用',
    description: '攻+2 志+1',
    effects: [
      { type: 'attr', key: 'str', value: 2 },
      { type: 'attr', key: 'will', value: 1 },
    ],
    tags: ['attack'],
    weight: 2,
  },
  {
    id: 'n_leg_cult',
    name: '传奇中型·灵台清明',
    kind: 'legendary_medium',
    professionId: 'any',
    professionName: '通用',
    description: '闭关 +12%，志+1',
    effects: [
      { type: 'cultivateMult', value: 0.12 },
      { type: 'attr', key: 'will', value: 1 },
    ],
    tags: ['cultivate'],
    weight: 2,
  },
]
